# Fuzzel launcher config — Gruvbox Dark Hard theme.

[main]
font=Hack Nerd Font Mono:size=14
lines=8
width=40
horizontal-pad=16
vertical-pad=12
inner-pad=4
prompt=>\s
icon-theme=Papirus-Dark

[colors]
background=1d2021ee
text=ebdbb2ff
prompt=fe8019ff
placeholder=a89984ff
input=ebdbb2ff
match=fabd2fff
selection=3c3836ff
selection-text=ebdbb2ff
selection-match=fabd2fff
border=fe8019ff
counter=928374ff

[border]
width=2
radius=6

[dmenu]
exit-immediately-if-empty=yes
